#!/bin/bash
read -p "This will destroy the MariaDB installation and its data. Do you want to continue?(y/n)" answer
if [ "$answer" == "n" ]
then
        exit
elif [ "$answer" == "y" ]
then
        dnf autoremove mariadb mariadb-server -y
        rm -rf /var/lib/mysql
        rm -rf /var/log/mariadb/mariadb.log
        rm -rf /var/run/mariadb/mariadb.pid
        rm -rf /etc/my.cnf.d
        echo "MariaDB removed completely"
else
        echo "UnKnown Option"
fi
